### ISSUE TITLE
Weird list formatting

### ISSUE THREAD

**Issue by mafredri** [shurcooL/markdownfmt#18]
It seems that the list formatting behaves a bit weirdly, there is actually a difference between having an extra newline in your list, separating that entry for the rest. I don't think its feasible to make the assumption that it should either be condensed or separated by newlines.

Output:

```markdown
test
====

1.	test
2.	test

	-	test

3.	test

4.	test

5.	test
```

Expected (original):

```markdown
test
====

1.	test
2.	test
	-	test
3.	test
4.	test
5.	test
```

**Comment by mafredri** [comment]
Sorry, this was actually due to a conflicting atom plugin (even though it was disabled). I'm getting the expected result after restarting Atom!

**Comment by shurcooL** [comment]
Ok, good to know.

However, please be aware that the Atom plugin has been deprecated and will be removed soon. See https://github.com/shurcooL/atom-markdown-format/pull/26 for motivation.
