### ISSUE TITLE
Paragraph unwrapping missing spaces

### ISSUE THREAD

**Issue by moorereason** [shurcooL/markdownfmt#20]
Given the following paragraphs:
```
text
[link](https://github.com)

text
*italic*

text
**bold**

text
***massive***

text
`noformat`
```

`markdownfmt` yields:

```
text[link](https://github.com)

text*italic*

text**bold**

text***massive***

text`noformat`
```

I expect it to yield:
```
text [link](https://github.com)

text *italic*

text **bold**

text ***massive***

text `noformat`
```

There may be other instances where formatting inside a paragraph gets rendered in a similar way.  I only tests these.

**Comment by shurcooL** [comment]
This looks like a legitimate bug. I agree with your expected output. Thanks for reporting.

I don't have a lot of bandwidth for this project, but I will try to look into it. If someone else is willing to dig into code (it's not my prettiest Go code), help is welcome.

**Comment by moorereason** [comment]
Can you give me some pointers?  I'm trying to understand how blackfriday+markdownfmt work together.  Which functions should I target?

If I add `out.WriteString(" ")` to [L370](https://github.com/shurcooL/markdownfmt/blob/7e22e584b4b3d63641783a6f46ee287f85327f65/markdown/main.go#L370), it seems to fix it, but I'm not sure what the ramifications are.  That change does cause the "Test" and "Example" tests to fail.

My edit:
```
369   if string(text) == "\n" { // TODO: See if this can be cleaned up... It's needed for lists.
370       out.WriteString(" ")
371       return
372   }
```
Do you remember what that TODO comment was about?  Also, how do I utilize the debug package?

**Comment by shurcooL** [comment]
Blackfriday is used to parse the Markdown. Markdownfmt provides a [`blackfriday.Renderer`](https://godoc.org/github.com/russross/blackfriday#Renderer) implementation which is used to render formatted Markdown (rather than HTML).

`NormalText` and `skipSpaceIfNeededNormalText` are very likely relevant. However, as you can see, it's not super clean. There are some hardcoded edge cases to fix lists, etc. The goal is to solve this, but not break existing tests.

**Comment by shurcooL** [comment]
I see that the problem does not occur for these cases:

```
text
text

[link](https://github.com)
text

*italic*
text

**bold**
text

***massive***
text

`noformat`
text
```

I would try to look into what causes the difference.

**Comment by shurcooL** [comment]
I have a fix for this.
