### ISSUE TITLE
Emacs plugin

### ISSUE THREAD

**Issue by nlamirault** [shurcooL/markdownfmt#27]
Hi,
i'm creating an Emacs plugin [emacs-markdown][1] for your project. It will be soon available into Melpa [PR3972][2].
Regards.

[1]: https://github.com/nlamirault/emacs-markdownfmt
[2]: https://github.com/melpa/melpa/pull/3972

**Comment by shurcooL** [comment]
Hi @nlamirault,

That's very cool! Thanks for making it and letting me know. :)

As soon as you're ready, feel free to make a PR and add it to the README [here](https://github.com/shurcooL/markdownfmt#editor-plugins).

Cheers!

**Comment by nlamirault** [comment]
Done. You could find the plugin here: http://melpa.org/#/markdownfmt

**Comment by shurcooL** [comment]
That's great! :D

Would you like to make a PR to add it to the Editor Plugins section in the README here?
