### ISSUE TITLE
Image title text stripped

### ISSUE THREAD

**Issue by jlevy** [shurcooL/markdownfmt#31]
There is an issue when markdownfmt is used on image links with title text, such as:
![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "This is the title text, which will be removed")

The title text (tool tip) following the URL is stripped away. Obviously, this is unfortunate as it is a destructive change on the source doc.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images

**Comment by shurcooL** [comment]
Thanks for reporting this, it sounds like a legitimate issue.

I'll only be able to look at this in a few days, after [dotGo](https://twitter.com/dotGoEu/status/783285853393133569).

**Comment by jlevy** [comment]
👍 Thanks! Based on a quick look it seems blackfriday knows how to parse the title but it doesn't get re-written out.

**Comment by jlevy** [comment]
👍
