### ISSUE TITLE
### type headers

### ISSUE THREAD

**Issue by anacrolix** [shurcooL/markdownfmt#37]
I assume the tool is intentionally quite opinionated. It doesn't handle headers that were indented ### and beyond. I'd love to know your reasoning for preferring the style it instead uses.

**Comment by shurcooL** [comment]
> I assume the tool is intentionally quite opinionated.

It is.

> It doesn't handle headers that were indented ### and beyond.

It should. Can you elaborate? What input, what did you expect to get, what did you get instead?

**Comment by shurcooL** [comment]
In fact, see this line in the test file:

https://github.com/shurcooL/markdownfmt/blob/10aae0a270abfb5d929ae6ca59c4b0ac0fa8f237/markdown/main_test.go#L169

**Comment by shurcooL** [comment]
Perhaps the problem is that you didn't have a space after the hashes, ala `###attempted header`? The space is strictly required.

**Comment by anacrolix** [comment]
I expected it to leave all the # style headers alone, or also rewrite my ### headers into the ---- and ==== underlined style it uses. It appears that it leaves h3 and further alone?

**Comment by shurcooL** [comment]
It's because the underlined styles exist for h1 and h2 only, so h3 has no choice but to use `###` style. See https://daringfireball.net/projects/markdown/syntax#header.

**Comment by anacrolix** [comment]
Ok thanks
