### ISSUE TITLE
Heads-up: markdownfmt is now packaged in FreeBSD

### ISSUE THREAD

**Issue by 0mp** [shurcooL/markdownfmt#50]
Just for your information.

Thank you for this awesome piece of software!

See here for more details: https://www.freshports.org/textproc/markdownfmt

**Comment by dmitshur** [comment]
Thanks for letting me know. I'm glad it's useful to people, however, I'm also sad because this project is nowhere near the high quality I wished it could reach, and I've stopped actively trying to improve it because of the high-effort-low-payoff ratio. So it's provided as-is now.

**Comment by 0mp** [comment]
@dmitshur I use it daily to lint my markdown files. It's a wonderful program. The way it integrates with Vim is just fantastic!

Thank you for your work :)
