### ISSUE TITLE
Does not work with code nested in blockquote

### ISSUE THREAD

**Issue by karelbilek** [shurcooL/markdownfmt#55]
Minimal example:

Input:

    > ```
    > Foo
    > ```
    
    
    ```
    foo
    ```

Output:

```
> ```
> > Foo
> > ```
>
>
> ```
>
> foo \`\`\`
```

**Comment by karel-3d** [comment]
It seems that it works when both code blocks are at the same level - that is, if both are in blockquote, or both outside of it.

But once one is inside blockquote and one outside, blackfriday loses its marbles

**Comment by karelbilek** [comment]
#56
