### ISSUE TITLE
renderer: Fenced Code Block info string should not trim to first word only.

### ISSUE THREAD

**Issue by bwplotka** [shurcooL/markdownfmt#58]
It's totally allowed by markdown language to have longer [info string](https://github.github.com/gfm/#info-string) that is not limited to a single word. I would love to leverage that in my tool, during formatting, but I can't as `markdownfmt` trims all to a single word.

Would you accept a PR that would leave the info string unchanged?

**Comment by dmitshur** [comment]
That sounds like a bug, fixing which is in scope. I have little bandwidth to do code review or fix bugs in this project, so it's hard to promise anything.

In general, I'd recommend picking a more active fork to contribute to instead. This issue may even get fixed if using blackfriday v2 (#39) or goldmark (#56).

> leave the info string unchanged

It should still trim the whitespace at the both ends.

**Comment by bwplotka** [comment]
> It should still trim the whitespace at the both ends.

agree.

Thanks!

I did that here: https://github.com/Kunde21/markdownfmt/pull/12
