### ISSUE TITLE
please add copyright :)

### ISSUE THREAD

**Issue by karelbilek** [shurcooL/markdownfmt#59]
Hello,

we want to put proper copyright to license of our fork, but there is none as there is no license file - there is a link to MIT license, but there is no actual copyright notice anywhere

(related to https://github.com/Kunde21/markdownfmt/issues/25 )

**Comment by dmitshur** [comment]
Thanks for reporting. I’ll fix this soon.

**Comment by karelbilek** [comment]
Thx. Added you to our fork MIT copyright :) 

(and thx for this project, even when we in the end rewrote almost everything, maybe except for the tests, good starting point)
