### ISSUE TITLE
Don't override unordered (bulleted) list symbols

### ISSUE THREAD

**Issue by exalted** [shurcooL/markdownfmt#6]
Markdown syntax allows either `*`, `-`, or `+` for unordered (bulleted) lists, but `markdownfmt` will override `*` or `+` with `-`s.

I think it is for the best if you'd stick to the user's personal preference.

**Comment by nemoDreamer** [comment]
So I'm guessing that's the same argument agains a configuration to use space indentation instead of tabs, especially in lists?

**Comment by shurcooL** [comment]
I prefer to avoid configuration, but I'm not necessarily opposed to using space indentation in lists. If you want to see that, can you open an issue and make a proposal?

I originally used spaces, but there were some issues and tabs seemed like an improvement, that's why I made the change. But if you have convincing arguments that spaces are indeed better, I will consider switching back.

**Comment by shurcooL** [comment]
@nemoDreamer See the commit message in 47b83b9786f84670e61df3af27803b96e59ec0e2 for the rationale to move from spaces to tabs in list indentation.

**Comment by nemoDreamer** [comment]
Thanks for the rationale, @shurcooL !
I agree that for aligning bullets and their hangning lines, tabs make so much more sense...
I've just seen the development community in general move away from tabs, so was looking for a way to still be able to use markdownfmt w/ existing space-aligned docs w/ commiting a big whitespace-change diff to the repo.
Low prio, though. No worries.

**Comment by shurcooL** [comment]
> was looking for a way to still be able to use markdownfmt w/ existing space-aligned docs w/ commiting a big whitespace-change diff to the repo.

I'd like to support that in some way if I can; can you please open a new issue about it so I don't forget and can think more about it? If you can provide more details and sample context, that'd be great too.

**Comment by nemoDreamer** [comment]
Will do.
